# CI on Mac OS for simple-messenger


name: simple-messenger-mac-os-

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: install clang-format
      run: brew install clang-format
    - name: install clang-tidy
      run: brew install llvm && ln -s "$(brew --prefix llvm)/bin/clang-tidy" "/usr/local/bin/clang-tidy"
    - name: format
      run: make clang_format
    - name: tidy
      run: make clang_tidy
    - name: build
      run: make
    - uses: actions/upload-artifact@v3
      with:
        name: simple-messenger
        path: |
          client: ./client
          server: ./server
          README: ./README.md

